services:
  nginx:
    image: nginx:1.27
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: "{DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "{DB_PASSWORD}"
      PMA_HOST: mysql
volumes:
  mysql-data:
